################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
i2c_functions/i2c_TM4C.obj: ../i2c_functions/i2c_TM4C.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/include" --include_path="A:/ti/StellarisWare" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=ccs="ccs" --define=EMPL_TARGET_TM4C --define=MPU9150 --define=EMPL --define=MPL_LOG_NDEBUG=1 --define=USE_DMP --define=ARM_MATH_CM4 --define=__FPU_PRESENT=1 --define=PART_LM4F232H5QD --define=TARGET_IS_BLIZZARD_RA1 --define=PART_TM4C123GE6PM -g --gcc --printf_support=full --diag_warning=225 --display_error_number --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="i2c_functions/i2c_TM4C.d_raw" --obj_directory="i2c_functions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

i2c_functions/i2c_functions.obj: ../i2c_functions/i2c_functions.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart/include" --include_path="A:/ti/StellarisWare" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/MPU_MPL_LM4F_TM4C_uart" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=ccs="ccs" --define=EMPL_TARGET_TM4C --define=MPU9150 --define=EMPL --define=MPL_LOG_NDEBUG=1 --define=USE_DMP --define=ARM_MATH_CM4 --define=__FPU_PRESENT=1 --define=PART_LM4F232H5QD --define=TARGET_IS_BLIZZARD_RA1 --define=PART_TM4C123GE6PM -g --gcc --printf_support=full --diag_warning=225 --display_error_number --gen_func_subsections=on --abi=eabi --ual --preproc_with_compile --preproc_dependency="i2c_functions/i2c_functions.d_raw" --obj_directory="i2c_functions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


