################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
MPU/core/mllite/data_builder.obj: ../MPU/core/mllite/data_builder.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/data_builder.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/hal_outputs.obj: ../MPU/core/mllite/hal_outputs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/hal_outputs.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/message_layer.obj: ../MPU/core/mllite/message_layer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/message_layer.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/ml_math_func.obj: ../MPU/core/mllite/ml_math_func.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/ml_math_func.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/mlmath.obj: ../MPU/core/mllite/mlmath.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/mlmath.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/mpl.obj: ../MPU/core/mllite/mpl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/mpl.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/results_holder.obj: ../MPU/core/mllite/results_holder.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/results_holder.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/start_manager.obj: ../MPU/core/mllite/start_manager.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/start_manager.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MPU/core/mllite/storage_manager.obj: ../MPU/core/mllite/storage_manager.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -O2 --fp_mode=relaxed --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/include" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/i2c_functions" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/stm32L" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/eMPL-hal" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mpl" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/eMPL" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/mllite" --include_path="/Users/crohan009/Documents/Stuff/USR18/code base/Data_extraction/LM4F_TM4C_uart/MPU/core/driver/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178" --include_path="/Applications/ti/TivaWare_C_Series-2.1.4.178/utils" --define=__FPU_PRESENT=1 --define=ARM_MATH_CM4 --define=USE_DMP --define=MPL_LOG_NDEBUG=1 --define=EMPL --define=MPU9150 --define=EMPL_TARGET_TM4C --define=ccs="ccs" --define=TARGET_IS_TM4C123_RA3 --define=PART_TM4C123GE6PM --gcc --abi=eabi --preproc_with_compile --preproc_dependency="MPU/core/mllite/storage_manager.d_raw" --obj_directory="MPU/core/mllite" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


